### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [AmineDiro/cria#3]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by AmineDiro** [comment]
solved in [ac03f5b](https://github.com/AmineDiro/cria/commit/ac03f5baf25f62e07d851c4943decc922c3e154b)
