### ISSUE TITLE
"git submodule update --init --recursive" requires ssh

### ISSUE THREAD

**Issue by snakewizardd** [AmineDiro/cria#4]
I am trying to get this running in Docker

Here is my current build

```
from ubuntu:latest

RUN apt-get update && apt-get install -y \
    sudo 

RUN apt-get update && \
    apt-get install -y \
    curl \
    build-essential \
    libssl-dev \
    pkg-config


# Install Rust and Cargo
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"


RUN yes | sudo apt install git 

RUN git clone https://github.com/AmineDiro/cria.git
WORKDIR /cria
#RUN yes | git submodule update --init --recursive

# Build the project using Cargo in release mode
#RUN cargo build --release

#COPY ggml-model-q4_0.bin .
```

Unfortunately, it seems like the ``` git submodule update --init --recursive ``` command is somehow interfacing with the repo via ssh

Have you considered maybe building this in a way that the dependencies can be installed without ssh?

![image](https://github.com/AmineDiro/cria/assets/83378208/96c9181d-8472-46b9-830f-510467b5214a)

**Comment by AmineDiro** [comment]
Hello just fixed this in the latest commit ! :) Hope this works

**Comment by snakewizardd** [comment]
Thanks bro :) 

I was able to get past that step and also start up the localhost API on 3000 

FYI seems like ```Llama-2``` is not a valid runtime command, but rather we must use ```Llama```

But seems like a basic POST request is hanging up for many hundreds of seconds

Docker build
```
from ubuntu:latest

RUN apt-get update && apt-get install -y \
    sudo 

RUN apt-get update && \
    apt-get install -y \
    curl \
    build-essential \
    libssl-dev \
    pkg-config


# Install Rust and Cargo
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"


RUN yes | sudo apt install git 

RUN echo 'hello'
RUN git clone https://github.com/AmineDiro/cria.git
WORKDIR /cria
RUN yes | git submodule update --init --recursive

# Build the project using Cargo in release mode
RUN cargo build --release

RUN echo 'hello'
WORKDIR /

COPY ggml-model-q4_0.bin .


EXPOSE 3000

#WORKDIR /cria/target/release 

#CMD ./cria Llama ggml-model-q4_0.bin
```

![image](https://github.com/AmineDiro/cria/assets/83378208/a986699b-d91f-4e38-80b1-de89c6d39b0c)
![image](https://github.com/AmineDiro/cria/assets/83378208/69d7db3b-a3c4-409c-9c7d-86af0512ed29)

**Comment by snakewizardd** [comment]
I did finally get a reply after a few minutes!

![image](https://github.com/AmineDiro/cria/assets/83378208/f81f5abf-9c8b-4d58-bb67-f30bb0df764a)

**Comment by AmineDiro** [comment]
Great ! You can speedup the inference by offloading layers to the GPU, you will need to add nvidia-docker runtime for nvidia gpus though

**Comment by snakewizardd** [comment]
> Great ! You can speedup the inference by offloading layers to the GPU, you will need to add nvidia-docker runtime for nvidia gpus though

Thanks for the advice. Unfortunately I am working with CPU :(

Still, I am glad that I was able to help in any way by providing a viable docker build for your setup. Best of luck homie
